In [1]:
import tensorflow as tf
from __future__ import print_function
import numpy as np


/usr/local/Cellar/python3/3.6.4_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)


## A1 Q1
Euclidean distance function, vectorized    

In [9]:
def euclideanDistance(x, z):
    '''
    We vectorized the operation with matrix operations
    the ||x - z ||^2 is = Sum(x - z)^2 = Sum from 1 to D
    of (x^2 - 2xz + z^2)
    
    x^2 = x^T times x
    z^2 = z^T times z
    we can find the sum of each row by using the reduce sum function
    
    sum of -2xz 
    we can use matrix multiplication, x times z^T to obtain xz,
    then multiply by -2
    '''
    n1 = x.shape[0]
    n2 = z.shape[0]    
    
    x_squared = tf.square(x)
    z_squared = tf.square(z) #tf.matmul(z ,tf.transpose(z))
    print("x_squared.eval()")
    print(x_squared.eval())
    ######coule be wrong here########
    x_2_sum = tf.reduce_sum(x_squared, 1)
    z_2_sum = tf.reduce_sum(z_squared, 1)
    
    x_2_sum = tf.transpose(x_2_sum)
    z_2_sum = tf.transpose(z_2_sum)
    #x_2_sum = tf.reshape(x_2_sum, [-1, 1])
    #z_2_sum = tf.reshape(z_2_sum, [-1, 1])
    print("x_2_sum.eval()")
    print(x_2_sum.eval())
    
    xz = tf.matmul(x, tf.transpose(z))
    #print(xz.eval())
    minus_2xz = tf.scalar_mul(-2, xz)
    #print(minus_2xz.eval())
 
    x_2_tile =tf.tile(tf.expand_dims(x_2_sum, 1), [1, n2])
    z_2_tile = tf.tile(tf.expand_dims(z_2_sum ,1), [1, n1])
    z_2_tile_T = tf.transpose(z_2_tile)
    print(x_2_tile.eval())
    print(z_2_tile_T.eval())
    
    result = x_2_tile + minus_2xz +z_2_tile_T
    
    return result

def squared_dist(A): 
    expanded_a = tf.expand_dims(A, 1)
    expanded_b = tf.expand_dims(A, 0)
    distances = tf.reduce_sum(tf.squared_difference(expanded_a, expanded_b), 2)
    return distances


def testi():
    A = tf.constant([[1, 1], [2,2], [3, 3]])
    B = tf.constant([[1, 1], [2, 2],[3,3]])
    res_mine = euclideanDistance(A, B)
    
    print("----my func----")
    print(res_mine.eval())
    print("---diff square---")
    res_lib = squared_dist(A)
    print(res_lib.eval())
    
with tf.Session() as sess1:
    testi()
    
    


x_squared.eval()
[[1 1]
 [4 4]
 [9 9]]
x_2_sum.eval()
[ 2  8 18]
[[ 2  2  2]
 [ 8  8  8]
 [18 18 18]]
[[ 2  8 18]
 [ 2  8 18]
 [ 2  8 18]]
----my func----
[[0 2 8]
 [2 0 2]
 [8 2 0]]
---diff square---
[[0 2 8]
 [2 0 2]
 [8 2 0]]


## A1 Q2
### part 1

| x1^T | x2^T | .... |
top k closest in x1^T indices are the neighbours


yˆ(x∗) = YTr∗, where r∗ = [r1,...,rN],rn = 1/k
0, otherwise.




In [20]:
#given starter code
import numpy as np
import matplotlib.pyplot as plt

# my code part1 responsibility
def nearestIndices(_dist_mat, _k):
    with tf.Session() as sess:
        #_dist_mat = tf.constant([ [4, 9], [16, 25] ], tf.int32)
        nearest_k = tf.nn.top_k(tf.negative(_dist_mat), _k)
        #print(_dist_mat.eval())
        print(nearest_k.indices.eval())
        indices_arr = nearest_k.indices.eval()
        print(type(indices_arr))
        return indices_arr

def responsibility(_neighbours, _k, _n ):
    respon = np.zeros(_n) #total number of data
    #find intersection of _data and _neighbours
    print(type(_neighbours))
    one_over_k = 1/_n
    for i in _neighbours:
        respon[i] +=1
        
    print(respon)
    
    
    
    

#unit testing
dist_mat = tf.constant([ 4, 9, 16, 25 ], tf.int32)
topk = nearestIndices(dist_mat, 2)
responsibility(dist_mat, 2, 4)



[0 1]
<class 'numpy.ndarray'>
<class 'tensorflow.python.framework.ops.Tensor'>


TypeError: 'Tensor' object is not iterable.

In [ ]:
np.random.seed(521)
Data = np.linspace(1.0 , 10.0 , num =100) [:, np. newaxis]
Target = np.sin( Data ) + 0.1 * np.power( Data , 2) \
         + 0.5 * np.random.randn(100 , 1)
randIdx = np.arange(100)
np.random.shuffle(randIdx)
trainData, trainTarget  = Data[randIdx[:80]], Target[randIdx[:80]]
validData, validTarget = Data[randIdx[80:90]], Target[randIdx[80:90]]
testData, testTarget = Data[randIdx[90:100]], Target[randIdx[90:100]]

def knn(_data, _target, _k):
    #nearest indices
    #responsbility
    #maximum responsibility
    
    