# P1 - Eucidean Distance

In [4]:
import numpy as np
import tensorflow as tf
from __future__ import print_function
import matplotlib.pyplot as plt

In [5]:
def euclidean_dist(x, z):
    
    #||x - z||^2 = x.T*x - 2*x*z.T + z.T*z
    
    x2 = tf.matmul(x ,tf.transpose(x))
    z2 = tf.matmul(z ,tf.transpose(z))
    
    x2_sum = tf.reduce_sum(x2, axis = 1)
    z2_sum = tf.reduce_sum(z2, axis = 1)
    
    xt = tf.transpose(x2_sum)
    zt = tf.transpose(z2_sum)
    
    xz = tf.matmul(x, tf.transpose(z))
    minus_xz = tf.scalar_mul(-2, xz)
    
    xt = tf.expand_dims(xt, axis = 1)
    zt = tf.expand_dims(zt, axis = 1)
    zt = tf.transpose(zt)
    
    xz2 = xt + zt + minus_xz
    
    return xz2

In [6]:
sess = tf.Session()

a = tf.constant([[1, 1], [2, 2], [3, 3], [4, 4]])
b = tf.constant([[2, 2], [3, 3], [4, 4]])

c = euclidean_dist(a, b)
print(sess.run(c))


[[48 62 76]
 [60 70 80]
 [72 78 84]
 [84 86 88]]


# P2 

In [8]:
def pairwise_dist(data1, data2):
    data1 = tf.convert_to_tensor(data1)
    data2 = tf.convert_to_tensor(data2)
    
    dist = euclidean_dist(data1, data2)
    return dist

def knn_predict(_trainData, _trainTarget, _X, _k):
    dist = pairwise_dist(_trainData, _X)
    near_k, near_id = tf.nn.top_k(dist, _k)
    respon = tf.gather(_trainData, near_id)
    respon = tf.reduce_mean(respon, axis = 1)
    
    return respon
    

In [13]:
sess = tf.Session()

a = tf.constant([[1, 1], [2, 2], [3, 3]])
b = tf.constant([[2, 2], [3, 3], [4, 4]])

c = pairwise_dist(a, b)
print(sess.run(c))

[[40 54 68]
 [44 54 64]
 [48 54 60]]


In [ ]:
def mse_loss(trainData, trainTarget, testData, testTarget):
    
    
    return loss

In [10]:
def plot(_trainData, _trainTarget):
    X = np.linspace(0.0, 11.0, num = 1000) [:, np.newaxis]
    X = tf.convert_to_tensor(X)
    
    k_list = [1, 3, 5, 50]
    
    for k in k_list:
        

In [7]:
np.random.seed(521)
Data = np.linspace(1.0 , 10.0 , num =100) [:, np. newaxis]
Target = np.sin( Data ) + 0.1 * np.power( Data , 2) \
+ 0.5 * np.random.randn(100 , 1)
randIdx = np.arange(100)
np.random.shuffle(randIdx)
trainData, trainTarget = Data[randIdx[:80]], Target[randIdx[:80]]
validData, validTarget = Data[randIdx[80:90]], Target[randIdx[80:90]]
testData, testTarget = Data[randIdx[90:100]], Target[randIdx[90:100]]

trainData = tf.convert_to_tensor(trainData)
trainTarget = tf.convert_to_tensor(trainTarget)
testData = tf.convert_to_tensor(testData)
testTarget = tf.convert_to_tensor(testTarget)
validData = tf.convert_to_tensor(validData)
validtarget = tf.convert_to_tensor(validTarget)