In [12]:
import numpy as np
import tensorflow as tf
from __future__ import print_function

In [35]:
def euclidean_dist(x, z):
    
    #||x - z||^2 = x.T*x - 2*x*z.T + z.T*z
    
    x2 = tf.matmul(x ,tf.transpose(x))
    z2 = tf.matmul(z ,tf.transpose(z))
    
    x2_sum = tf.reduce_sum(x2, axis = 1)
    z2_sum = tf.reduce_sum(z2, axis = 1)
    
    xt = tf.transpose(x2_sum)
    zt = tf.transpose(z2_sum)
    
    xz = tf.matmul(x, tf.transpose(z))
    minus_xz = tf.scalar_mul(-2, xz)
    
    xt = tf.expand_dims(xt, axis = 1)
    zt = tf.expand_dims(zt, axis = 1)
    zt = tf.transpose(zt)
    
    xz2 = xt + zt + minus_xz
    
    return xz2

In [43]:
sess = tf.Session()

a = tf.constant([[1, 1], [2, 2], [3, 3], [4, 4]])
b = tf.constant([[1, 1], [2, 2], [3, 3]])

c = euclidean_dist(a, b)
print(sess.run(c))


[[28 36 44]
 [44 48 52]
 [60 60 60]
 [76 72 68]]
